// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'request.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProxyServer>>
abstract class ProxyServer implements RustOpaqueInterface {
  Stream<RoxyRequest> listen();

  factory ProxyServer({required String ip, required int port}) =>
      RustLib.instance.api.crateApiHttpProxyProxyServerNew(ip: ip, port: port);
}
